import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outFile = path.join(rootDir, "src/assets/generated.ts");

function read(relPath: string): string {
  return fs.readFileSync(path.join(rootDir, relPath), "utf8");
}

function mimeForFont(fileName: string): string {
  if (fileName.endsWith(".woff2")) return "font/woff2";
  if (fileName.endsWith(".woff")) return "font/woff";
  if (fileName.endsWith(".ttf")) return "font/ttf";
  return "application/octet-stream";
}

function inlineKatexFonts(css: string): string {
  return css.replace(/url\(fonts\/([^)]+)\)/g, (_, fileName: string) => {
    const fontPath = path.join(rootDir, "node_modules/katex/dist/fonts", fileName);
    const encoded = fs.readFileSync(fontPath).toString("base64");
    return `url(data:${mimeForFont(fileName)};base64,${encoded})`;
  });
}

const assets = {
  cherryCss: read("node_modules/cherry-markdown/dist/cherry-markdown.markdown.min.css"),
  echartsJs: read("node_modules/echarts/dist/echarts.min.js"),
  mermaidJs: read("node_modules/mermaid/dist/mermaid.min.js"),
  katexJs: read("node_modules/katex/dist/katex.min.js"),
  katexCss: inlineKatexFonts(read("node_modules/katex/dist/katex.min.css")),
};

const content = `// Generated by scripts/generate-assets.ts. Do not edit by hand.
export const assets = ${JSON.stringify(assets)};
`;

fs.writeFileSync(outFile, content);
console.log(`Wrote ${path.relative(rootDir, outFile)}`);
